name: docker build image and push
on:
  push:
    branches:
      - oyogbeche

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t oyogbeche/qrcode-backend:latest ./api/
      - name: docker push
        run: |
          docker login -u oyogbeche -p ${{secrets.DOCKERHUB_TOKEN}}
          docker push oyogbeche/qrcode-backend:latest 

